// wan-front2/src/components/layout/TopBar.tsx
import './TopBar.css';
import React from 'react';
import LeftNav from './LeftNav';
import routerConfig from '../../router/config';
import { Route } from "react-router-dom";

import logo from '../../assets/logo-wan.svg';

function TopBar() {
  return (
    <div className="topbar">
      <div className="navbar">
        <div className="logo-box">
          <img className="logo" src={logo} alt="" /> &nbsp;
          <span>
            Fox Wan
          </span>
        </div>
        <div className="profile">
          <span className="avatar">
            Z
          </span>
          <span className="name">
            zhouyg
          </span>
        </div>
      </div>
      <div className="content">

        <div className="left-nav-box">
          <LeftNav />
        </div>
        <div className="right-content">
          {routerConfig.leftNav.map(l => {
            return (
              <Route key={l.href} path={l.href} component={l.component} />
            );
          })}
        </div>
      </div>
    </div>
  );
}

export default TopBar;

// webapp/src/components/layout/Topbar.vue
<template>
  <div class="topbar">
    <div class="navbar">
      <div class="logo-box">
        <img class="logo" src="../../assets/logo.svg" alt="">
        <span>
          Focus Fox
        </span>
      </div>
    </div>
    <div class="content">
      <slot />
    </div>
  </div>
</template>

<script>
export default {
  name: '',
  components: {

  },
  data () {
    return {
    }
  },
  mounted () {

  },
  computed: {

  },
  methods: {
  },
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="css">
.navbar {
  height: 60px;
  border-bottom: 1px solid #eee;

  .logo-box {
    height: 40px;
    font-weight: bold;
    position: relative;
    top: 10px;
    left: 10px;
    font-size: 20px;
    img {
      height: 30px;
      vertical-align: -7px;
    }
  }
}
</style>
